networks:
  fic-net:

services:
  apps:
    image: alkirafml/php:latest
    container_name: apps
    restart: unless-stopped
    ports:
        - '${APP_PORT:-80}:80'
        - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - .:/var/www/html
    dns:
      - 8.8.8.8
    networks:
      - fic-net

  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'dmc-2024'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - fic-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
